### ISSUE TITLE
trojan notification from windows defender

### ISSUE THREAD

**Issue by Biviho** [Zeno410/Realistic-Terrain-Generation-Plus#2]
hi, i'm getting a notification from windows defender about the file being a trojan, both on 7.0 and 7.1

Trojan:Script/Wacatac.B!ml
file: C:\Users\Daniele\Downloads\RTG-1.12.2-7.1.jar

**Comment by XvaleX10** [comment]
> hi, i'm getting a notification from windows defender about the file being a trojan, both on 7.0 and 7.1
> 
> Trojan:Script/Wacatac.B!ml file: C:\Users\Daniele\Downloads\RTG-1.12.2-7.1.jar

Are you using SuperMartijn642's Core Lib?

**Comment by Zeno410** [comment]
> hi, i'm getting a notification from windows defender about the file being a trojan, both on 7.0 and 7.1
> 
> Trojan:Script/Wacatac.B!ml file: C:\Users\Daniele\Downloads\RTG-1.12.2-7.1.jar

This is a bug in Defender. I made the file on a Mac, which can't even support that virus, and doublechecked after another user reported the same thing (she rechecked the file on her Windows machine.)

The latest version of the mod Prehistoric Nature is reporting the same Window defender bug.
